/**
 * build.mjs
 * Reads normalised W3C DTCG source tokens (figma + manual), merges them,
 * and produces platform-specific outputs.
 *
 * Usage:
 *   node scripts/build.mjs
 *
 * Inputs:
 *   tokens/primitives.figma.json   (auto-generated by normalize.mjs)
 *   tokens/primitives.manual.json  (hand-maintained: typography, shadow, motion)
 *
 * Outputs per platform:
 *   dist/<platform>/primitives.js   (ESM — consumable by any bundler)
 *   dist/<platform>/primitives.d.ts (TypeScript declarations with literal types)
 *   dist/web/primitives.css         (CSS custom properties)
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { flatten } from "./lib/parser.mjs";
import { mergeTokenSources } from "./lib/merge.mjs";
import { transformValue as webTransform } from "./lib/transforms/web.mjs";
import { transformValue as nativeTransform } from "./lib/transforms/native.mjs";
import { format as formatCSS } from "./lib/formatters/css.mjs";
import { format as formatTailwind } from "./lib/formatters/tailwind.mjs";
import { format as formatNative } from "./lib/formatters/native.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// ── .ts → .js / .d.ts converters ────────────────────────────────────────────

/**
 * Convert our generated .ts to .js (ESM).
 * Our .ts files only contain `export const X = {...} as const;` and `export type`.
 *   - Strip `as const` assertions
 *   - Remove `export type` blocks entirely (not runtime)
 */
function tsToJs(tsContent) {
  return tsContent
    // Remove entire `export type X = { ... };` blocks
    .replace(/^export type \w+ = \{[\s\S]*?^\};$/gm, "")
    // Strip `as const` type assertions
    .replace(/ as const;/g, ";")
    // Clean up consecutive blank lines
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd() + "\n";
}

/**
 * Convert our generated .ts to .d.ts.
 *   - `export const X = { ... } as const;`
 *     → keep value inline so TS infers literal types
 *   - `export type X = { ... };`
 *     → kept as-is
 */
function tsToDts(tsContent) {
  return tsContent
    .replace(/^export const (\w+) = /gm, "export declare const $1: ")
    .replace(/ as const;/g, ";");
}

// ── Sources ──────────────────────────────────────────────────────────────────

const FIGMA_SOURCE = resolve(ROOT, "tokens/primitives.figma.json");
const MANUAL_SOURCE = resolve(ROOT, "tokens/primitives.manual.json");

// ── Merge ────────────────────────────────────────────────────────────────────

const figmaTokens = JSON.parse(readFileSync(FIGMA_SOURCE, "utf-8"));
const manualTokens = JSON.parse(readFileSync(MANUAL_SOURCE, "utf-8"));

const { merged, warnings } = mergeTokenSources(figmaTokens, manualTokens);

for (const w of warnings) console.log(w);

// ── Flatten ──────────────────────────────────────────────────────────────────

const webTokens = flatten(merged, { stripExtensions: true });
const nativeTokens = flatten(merged, { stripExtensions: false });

console.log(`Parsed ${webTokens.length} tokens\n`);

// ── Outputs ──────────────────────────────────────────────────────────────────

function writeWithDeclarations(basePath, tsContent) {
  const dir = dirname(basePath);
  mkdirSync(dir, { recursive: true });

  const jsPath = basePath.replace(/\.ts$/, ".js");
  const dtsPath = basePath.replace(/\.ts$/, ".d.ts");

  writeFileSync(jsPath, tsToJs(tsContent), "utf-8");
  writeFileSync(dtsPath, tsToDts(tsContent), "utf-8");

  console.log(`  ✓ ${jsPath}`);
  console.log(`  ✓ ${dtsPath}`);
}

// CSS — standalone, no .js/.d.ts needed
const cssPath = resolve(ROOT, "dist/web/primitives.css");
mkdirSync(dirname(cssPath), { recursive: true });
writeFileSync(cssPath, formatCSS(webTokens, webTransform), "utf-8");
console.log(`  ✓ ${cssPath}`);

// Web (Tailwind config)
const webTs = formatTailwind(webTokens);
writeWithDeclarations(resolve(ROOT, "dist/web/primitives.ts"), webTs);

// Native (React Native / Unistyles)
const nativeTs = formatNative(nativeTokens, nativeTransform);
writeWithDeclarations(resolve(ROOT, "dist/native/primitives.ts"), nativeTs);

console.log("\nDone.");
