/**
 * formatters/native.mjs
 * Generates a TypeScript file for React Native / Unistyles consumption.
 *
 * Direct values (no CSS var references):
 *   export const colors = { white: '#FFFFFF', ... } as const;
 *   export const space = { 0: 0, 4: 16, ... } as const;
 *
 * Complex values like shadow are serialised as nested objects.
 * Includes full Primitives type export for Unistyles theme typing.
 */

import { groupByTopLevel } from "../parser.mjs";

/**
 * Build nested object from flat tokens with transformed values.
 */
function buildNestedObject(tokens, transformValue) {
  const root = {};

  for (const token of tokens) {
    const subPath = token.path.slice(1);
    const value = transformValue(token);

    let current = root;
    for (let i = 0; i < subPath.length - 1; i++) {
      const key = subPath[i];
      if (!(key in current)) current[key] = {};
      current = current[key];
    }
    current[subPath[subPath.length - 1]] = value;
  }

  return root;
}

/**
 * Serialize to TypeScript with proper quoting.
 * Handles nested objects, arrays, strings, and numbers.
 */
function serializeToTS(obj, indent = 2) {
  function inner(val, depth) {
    const pad = " ".repeat(depth * indent);
    const padInner = " ".repeat((depth + 1) * indent);

    if (val === null || val === undefined) return "null";
    if (typeof val === "string") return `'${val}'`;
    if (typeof val === "number") return String(val);
    if (typeof val === "boolean") return String(val);

    // Arrays
    if (Array.isArray(val)) {
      if (val.length === 0) return "[]";
      // Simple array of primitives → inline
      if (val.every((v) => typeof v !== "object")) {
        return `[${val.map((v) => (typeof v === "string" ? `'${v}'` : v)).join(", ")}]`;
      }
      // Array of objects → multiline
      const items = val.map((v) => `${padInner}${inner(v, depth + 1)}`);
      return `[\n${items.join(",\n")}\n${pad}]`;
    }

    // Objects
    const entries = Object.entries(val);
    if (entries.length === 0) return "{}";

    const lines = ["{"];
    for (const [key, child] of entries) {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
      lines.push(`${padInner}${safeKey}: ${inner(child, depth + 1)},`);
    }
    lines.push(`${pad}}`);
    return lines.join("\n");
  }

  return inner(obj, 0);
}

/**
 * @param {import('../parser.mjs').FlatToken[]} tokens
 * @param {(token: import('../parser.mjs').FlatToken) => *} transformValue
 * @returns {string} TypeScript file content
 */
export function format(tokens, transformValue) {
  const groups = groupByTopLevel(tokens);
  const parts = [
    "// Auto-generated by design-tokens build pipeline",
    "// Do not edit manually",
    "",
  ];

  const exportNames = [];

  for (const [groupKey, groupTokens] of groups) {
    const nested = buildNestedObject(groupTokens, transformValue);
    parts.push(`export const ${groupKey} = ${serializeToTS(nested)} as const;`);
    parts.push("");
    exportNames.push(groupKey);
  }

  // Generate Primitives type
  parts.push("export type Primitives = {");
  for (const name of exportNames) {
    parts.push(`  ${name}: typeof ${name};`);
  }
  parts.push("};");
  parts.push("");

  return parts.join("\n");
}
