/**
 * formatters/tailwind.mjs
 * Generates a TypeScript file for Tailwind theme config.
 *
 * Each token group is exported as a nested object referencing CSS variables:
 *   export const colors = { white: 'var(--colors-white)', ... } as const;
 *
 * Group name mapping to Tailwind theme keys:
 *   colors      → colors
 *   space       → spacing
 *   radius      → borderRadius
 *   borderWidth → borderWidth
 *   opacity     → opacity
 *   zIndex      → zIndex
 */

import { groupByTopLevel } from "../parser.mjs";

/** camelCase → kebab-case for CSS var names */
function toKebab(str) {
  return str.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/** Build CSS var reference */
function cssVarRef(path) {
  const name = path
    .map((s) => {
      const kebab = toKebab(s);
      return kebab.includes(".") ? kebab.replace(/\./g, "\\.") : kebab;
    })
    .join("-");
  return `var(--${name})`;
}

/** DTCG group → Tailwind theme key */
const TAILWIND_KEY_MAP = {
  colors: "colors",
  space: "spacing",
  radius: "borderRadius",
  borderWidth: "borderWidth",
  opacity: "opacity",
  zIndex: "zIndex",
  fontFamily: "fontFamily",
  fontWeight: "fontWeight",
  fontSize: "fontSize",
  lineHeight: "lineHeight",
  letterSpacing: "letterSpacing",
  shadow: "boxShadow",
  duration: "transitionDuration",
  easing: "transitionTimingFunction",
};

/**
 * Build nested object from flat tokens.
 * ['colors', 'neutral', '500'] with group='colors'
 * → subPath = ['neutral', '500']
 * → { neutral: { 500: value } }
 */
function buildNestedObject(tokens) {
  const root = {};

  for (const token of tokens) {
    // subPath = path without the top-level group key
    const subPath = token.path.slice(1);
    const ref = cssVarRef(token.path);

    let current = root;
    for (let i = 0; i < subPath.length - 1; i++) {
      const key = subPath[i];
      if (!(key in current)) current[key] = {};
      current = current[key];
    }
    current[subPath[subPath.length - 1]] = ref;
  }

  return root;
}

/**
 * Serialize a JS object to TypeScript source string with proper indentation.
 */
function serializeToTS(obj, indent = 2) {
  function inner(val, depth) {
    const pad = " ".repeat(depth * indent);
    const padInner = " ".repeat((depth + 1) * indent);

    if (typeof val === "string") {
      return `'${val}'`;
    }
    if (typeof val === "number") {
      return String(val);
    }
    if (typeof val !== "object" || val === null) {
      return String(val);
    }

    const entries = Object.entries(val);
    if (entries.length === 0) return "{}";

    const lines = ["{"];
    for (const [key, child] of entries) {
      // Quote keys that aren't valid JS identifiers
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
      lines.push(`${padInner}${safeKey}: ${inner(child, depth + 1)},`);
    }
    lines.push(`${pad}}`);
    return lines.join("\n");
  }

  return inner(obj, 0);
}

/**
 * @param {import('../parser.mjs').FlatToken[]} tokens
 * @returns {string} TypeScript file content
 */
export function format(tokens) {
  const groups = groupByTopLevel(tokens);
  const parts = [
    "// Auto-generated by design-tokens build pipeline",
    "// Do not edit manually",
    "",
  ];

  for (const [groupKey, groupTokens] of groups) {
    const twKey = TAILWIND_KEY_MAP[groupKey] ?? groupKey;
    const nested = buildNestedObject(groupTokens);
    parts.push(`export const ${twKey} = ${serializeToTS(nested)} as const;`);
    parts.push("");
  }

  return parts.join("\n");
}
